package hibernate.controller;

import hibernate.model.User;
import hibernate.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller

//PATH ZNACZY,ZE do calej metody ponizej bedziemy mieli rozszerzenie /demo  w linku url

@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path)
public class MainController {

//    /demo/add?name=damian&email=maciekrplacek@gmail.com
    //   ?   sluzy do implementowania  w htmlu


    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    //user repository musimy stworzyc kmlase by moc sie odniesc do niej


    @GetMapping(path = "/add") // Map ONLY GET Requests
    public @ResponseBody
    String addNewUser(@RequestParam String name
            , @RequestParam String email) {

        //daje nam mozliwosc implementowania  zeby sie odniesc do wartosci musimy dac ? pozniej nazwa wartosci(np name) = dajemy wartosc = Maciek
        // pozniej dajemy & zeby dodac kolejny odnosnik
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName(name);
        n.setEmail(email);
        userRepository.save(n);   //zapisuje do bazy daynch userRepository.save(n)
        return "Saved";
    }

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();      //znajduje wszystkich userow w bazie danych   // czyli robic selecta
    }
}